// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fgzieygxpivjxgdsufso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnemlleWd4cGl2anhnZHN1ZnNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MjUyOTksImV4cCI6MjA2OTIwMTI5OX0.Tivxp0SL1Laug0fLt1OIDfRVxvBwwHqK7-zIpZw5zUk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});